spring:
    datasource:
        druid:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:8066/MYCAT_ORDERS
            driver-class-name: com.mysql.jdbc.Driver

    # 配置 redis 用于获取分布式主键
    redis:
        host: 127.0.0.1
        password: abcd1234
        port: 6379
        database: 1


mybatis:
    type-aliases-package: com.xiao.mycat.orders.entity
    mapper-locations: classpath:mapper/*Mapper.xml



