spring:
    datasource:
        druid:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:8066/MYCAT_USERS
            driver-class-name: com.mysql.jdbc.Driver


mybatis:
    type-aliases-package: com.xiao.mycat.demo.entity
    mapper-locations: classpath:mapper/*Mapper.xml

